In [1]:
!pip install -U pip transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 88.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 122.9 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
  Attempting uninstall: transformers
    Found existing installation: transformers 4.56.2
    Uninstalling transformers-4.56.2:
      Successfully uninstalled transformers-4.56.2


In [2]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

In [3]:
checkpoint = 'facebook/nllb-200-distilled-600M'

In [4]:
model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [5]:
print(model)

M2M100ForConditionalGeneration(
  (model): M2M100Model(
    (shared): M2M100ScaledWordEmbedding(256206, 1024, padding_idx=1)
    (encoder): M2M100Encoder(
      (embed_tokens): M2M100ScaledWordEmbedding(256206, 1024, padding_idx=1)
      (embed_positions): M2M100SinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-11): 12 x M2M100EncoderLayer(
          (self_attn): M2M100Attention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): ReLU()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
       

In [6]:
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px

from sklearn.decomposition import PCA

In [7]:
print(f'2π = {2*np.pi:.2f}')

2π = 6.28


In [8]:
print(f'π/2 = {np.pi/2:.2f}')

π/2 = 1.57


In [11]:
length = np.pi/2
length

1.5707963267948966

In [12]:
np.sin(length)

np.float64(1.0)

In [13]:
# Generate angles from 0 to 2*pi (หน่วยเรเดียน) มีค่าประมาณ 0 ถึง 6.2831
theta = np.linspace(0, 2*np.pi, 1000)

# Calculate x and y coordinates for the unit circle
x = np.cos(theta)
y = np.sin(theta)

fig = go.Figure(data=go.Scattergl(
    x=x,
    y=y,
    mode='lines',
    hoverinfo='text',
    text=[f'x: {xi:.3f}<br>y: {yi:.3f}' for xi, yi in zip(x, y)]
))

# Set layout for the unit circle
fig.update_layout(
    title="Unit Circle with Cosine (x) and Sine (y) Values",
    xaxis_title="X (Cosine)",
    yaxis_title="Y (Sine)",
    xaxis=dict(range=[-1.2, 1.2], constrain="domain"),
    yaxis=dict(scaleanchor="x", scaleratio=1, range=[-1.2, 1.2]),
    hovermode='closest',
    width=600,
    height=600,
)

fig.add_shape(type="circle",
    xref="x", yref="y",
    x0=-1, y0=-1, x1=1, y1=1,
    line_color="LightSeaGreen",
    fillcolor="PaleTurquoise",
    opacity=0.2,
    layer="below"
)


fig.show()

In [14]:
amplitude = 1.0
frequency = 1.0
duration = 1
num_points = 1000

# Generate time data
t = np.linspace(0, duration, num_points)
t.shape

(1000,)

In [15]:
fig = go.Figure(data=go.Scatter(y=t, mode='lines'))

fig.update_layout(
    title="Time (t)",
    xaxis_title="Index",
    yaxis_title="Time [s]",
)

fig.show()

In [16]:
2 * np.pi * t

array([0.        , 0.00628947, 0.01257895, 0.01886842, 0.0251579 ,
       0.03144737, 0.03773685, 0.04402632, 0.0503158 , 0.05660527,
       0.06289475, 0.06918422, 0.0754737 , 0.08176317, 0.08805265,
       0.09434212, 0.1006316 , 0.10692107, 0.11321055, 0.11950002,
       0.1257895 , 0.13207897, 0.13836845, 0.14465792, 0.15094739,
       0.15723687, 0.16352634, 0.16981582, 0.17610529, 0.18239477,
       0.18868424, 0.19497372, 0.20126319, 0.20755267, 0.21384214,
       0.22013162, 0.22642109, 0.23271057, 0.23900004, 0.24528952,
       0.25157899, 0.25786847, 0.26415794, 0.27044742, 0.27673689,
       0.28302637, 0.28931584, 0.29560531, 0.30189479, 0.30818426,
       0.31447374, 0.32076321, 0.32705269, 0.33334216, 0.33963164,
       0.34592111, 0.35221059, 0.35850006, 0.36478954, 0.37107901,
       0.37736849, 0.38365796, 0.38994744, 0.39623691, 0.40252639,
       0.40881586, 0.41510534, 0.42139481, 0.42768429, 0.43397376,
       0.44026323, 0.44655271, 0.45284218, 0.45913166, 0.46542

In [17]:
y = np.sin(2 * np.pi * t)

In [45]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=t, y=y, mode='lines', name='Sine Wave'))

fig.update_layout(
    title="Sine Wave",
    xaxis_title="Time [s]",
    yaxis_title="Amplitude",
)

fig.show()

In [20]:
y_cos = np.cos(2 * np.pi * t)

fig = go.Figure()

fig.add_trace(go.Scatter(x=t, y=y, mode='lines', name='Sine Wave'))
fig.add_trace(go.Scatter(x=t, y=y_cos, mode='lines', name='Cosine Wave'))

fig.update_layout(
    title="Sine and Cosine Wave",
    xaxis_title="Time [s]",
    yaxis_title="Amplitude",
)

fig.show()

In [21]:
frequencies_to_compare = [1.0, 2.0, 3.0]
num_rows = len(frequencies_to_compare)

fig = make_subplots(rows=num_rows, cols=1, subplot_titles=[f'Sine Wave (Frequency = {freq})' for freq in frequencies_to_compare])

# Generate and add sine waves for each frequency
for i, freq in enumerate(frequencies_to_compare):
    y = amplitude * np.sin(2 * np.pi * freq * t)
    fig.add_trace(go.Scatter(x=t, y=y, mode='lines', name=f'Freq = {freq}'),
                  row=i + 1, col=1)

fig.update_layout(height=300 * num_rows, title_text="Comparison of Sine Waves with Different Frequencies")

for i in range(num_rows):
    fig.update_yaxes(title_text="Amplitude", row=i + 1, col=1)

fig.show()

In [23]:
frequencies_to_compare = [3, 2, 1]
num_rows = len(frequencies_to_compare)
num_cols = 2

x_range = 20
num_points = 1000
x = np.linspace(0, x_range, num_points)

subplot_titles = []
for freq in frequencies_to_compare:
    subplot_titles.append(f'Sine Wave (Freq = {freq})')
    subplot_titles.append(f'Cosine Wave (Freq = {freq})')

# Create subplots
fig = make_subplots(
    rows=num_rows,
    cols=num_cols,
    subplot_titles=subplot_titles,
    vertical_spacing=0.08,
    horizontal_spacing=0.1
)

# Define colors for each frequency
colors = ['#636EFA', '#EF553B', '#00CC96', '#AB63FA', '#FFA15A']

# Generate and add sine and cosine waves for each frequency
for i, freq in enumerate(frequencies_to_compare):
    # Sine wave data (left column)
    y_sin = np.sin(2 * np.pi * freq * (x / x_range))
    fig.add_trace(
        go.Scatter(
            x=x,
            y=y_sin,
            mode='lines',
            name=f'Sine Freq = {freq}',
            line=dict(color=colors[i], width=2),
            showlegend=False
        ),
        row=i + 1, col=1
    )

    # Cosine wave data (right column)
    y_cos = np.cos(2 * np.pi * freq * (x / x_range))
    fig.add_trace(
        go.Scatter(
            x=x,
            y=y_cos,
            mode='lines',
            name=f'Cosine Freq = {freq}',
            line=dict(color=colors[i], width=2),
            showlegend=False
        ),
        row=i + 1, col=2
    )

fig.update_layout(
    height=300 * num_rows,
    title_text="Comparison of Sine and Cosine Waves with Different Frequencies",
    title_font_size=20,
    showlegend=False
)

for i in range(num_rows):
    # Left column (Sine)
    fig.update_xaxes(
        title_text="Token Position",
        range=[0, x_range],
        gridcolor='lightgray',
        row=i + 1,
        col=1
    )
    fig.update_yaxes(
        title_text="Amplitude",
        range=[-1.2, 1.2],
        gridcolor='lightgray',
        row=i + 1,
        col=1
    )

    # Right column (Cosine)
    fig.update_xaxes(
        title_text="Position",
        range=[0, x_range],
        gridcolor='lightgray',
        row=i + 1,
        col=2
    )
    fig.update_yaxes(
        title_text="Amplitude",
        range=[-1.2, 1.2],
        gridcolor='lightgray',
        row=i + 1,
        col=2
    )

fig.write_html('sine_cosine_waves_comparison.html')
fig.show()

In [24]:
# ฟังก์ชันสร้าง Positional Encoding (Vaswani et al., 2017)
# y = amplitude * np.sin(2 * np.pi * frequency * t)

# position ทำหน้าที่เหมือน t (เวลาหรือ index token)
# angle_rates ทำหน้าที่เหมือนความถี่ของคลื่นในแต่ละ dim

def positional_encoding(position: int, d_model: int) -> np.ndarray:
    dims = np.arange(d_model)
    angle_rates = 1.0 / np.power(10000.0, (dims // 2) * 2 / d_model)
    angles = position * angle_rates
    pe = np.zeros(d_model, dtype=np.float64)
    pe[0::2] = np.sin(angles[0::2])   # even index → sin
    pe[1::2] = np.cos(angles[1::2])   # odd index  → cos
    return pe

def positional_encoding_matrix(num_tokens: int, d_model: int) -> np.ndarray:
    return np.stack([positional_encoding(i, d_model) for i in range(num_tokens)], axis=0)

In [25]:
def plot_positional_heatmap_plotly(num_tokens=50, d_model=64):
    pe_mat = positional_encoding_matrix(num_tokens, d_model)
    fig = px.imshow(
        pe_mat,
        color_continuous_scale="RdBu",
        labels=dict(x="Dimension", y="Token Position", color="Value (sin/cos)"),
        title=f"Positional Encoding Heatmap (Tokens 0–{num_tokens-1}, {d_model} dims)"
    )
    fig.update_layout(height=500, width=900)
    fig.show()

plot_positional_heatmap_plotly(num_tokens=20, d_model=10)

In [26]:
max_sequence_length = 75
embedding_dimension = 1024

pe_mat = positional_encoding_matrix(max_sequence_length, embedding_dimension)
pe_mat.shape

(75, 1024)

In [27]:
pca = PCA(n_components=3)

positional_encoding_pca = pca.fit_transform(pe_mat)

print(positional_encoding_pca.shape)
print(positional_encoding_pca[:5])
print("\nExplained variance ratio by the first three components", pca.explained_variance_ratio_)

(75, 3)
[[6.82951423 5.25607347 4.40186343]
 [7.25982086 5.6693082  4.87691459]
 [7.61762811 5.97038482 5.19856805]
 [7.88633462 6.12885614 5.32554384]
 [8.08012269 6.15987562 5.27197024]]

Explained variance ratio by the first three components [0.23002542 0.13361099 0.0900139 ]


In [28]:
fig_pca_scatter_3d = go.Figure(data=go.Scatter3d(
    x=positional_encoding_pca[:, 0],
    y=positional_encoding_pca[:, 1],
    z=positional_encoding_pca[:, 2],
    mode='markers+text',
    text=[str(pos) for pos in range(max_sequence_length)], # Add text labels for each position
    textposition="bottom center",
    marker=dict(
        size=5,
        color=np.arange(max_sequence_length), # Color points by position
        colorscale='Viridis',
        opacity=0.8
    )
))

fig_pca_scatter_3d.update_layout(
    title='PCA Projection of Positional Encoding (3D)',
    scene = dict(
        xaxis_title='Principal Component 1',
        yaxis_title='Principal Component 2',
        zaxis_title='Principal Component 3'
    ),
    margin=dict(l=0, r=0, b=0, t=40),
    height=700
)

fig_pca_scatter_3d.show()

In [29]:
max_sequence_length = 75
embedding_dimension = 1024

pe_values = pe_mat.flatten()

fig_hist = px.histogram(pe_values, nbins=100, title='Distribution of Positional Encoding Values')

fig_hist.update_layout(
    xaxis_title='Value',
    yaxis_title='Count',
    bargap=0.05,
    showlegend=False
)

fig_hist.show()

In [30]:
print("Positional encoding matrix")
print("Min", np.min(pe_mat))
print("Max", np.max(pe_mat))
print("Average", np.average(pe_mat))

Positional encoding matrix
Min -0.9999999983004432
Max 1.0
Average 0.37357085713127014


In [31]:
plot_positional_heatmap_plotly(num_tokens=75, d_model=1024)

In [32]:
token_embedding_layer = model.model.encoder.embed_tokens
token_embedding_layer.weight.shape

torch.Size([256206, 1024])

In [33]:
long_sentence = "In the vast realm of natural language processing, understanding the nuances of how models handle sequential data is crucial. Positional encoding plays a vital role in providing this essential information to the model, allowing it to differentiate between words at different positions in a sentence, which is fundamental for tasks like translation, summarization, and text generation."


In [34]:
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

In [35]:
tokens = tokenizer(long_sentence, return_tensors="pt")

print(tokens['input_ids'][0])

tensor([256047,    717,    349,  14430,  12284, 248070,    452,  25307,  65445,
        157278, 248079, 133930,    349,    713,  75831,    452,  11657, 141057,
         47274, 116914, 124785,   6067,    248, 182071, 248075,  12013,  58409,
         12025, 246156,   3054,    705,      9, 104781,  76065,    108, 174693,
          3423, 140515,  18781,    202,    349,  14916, 248079,  82935,     87,
           796,    202,  53054,    502,  25914,  51744,    230,  30158, 199073,
           108,      9, 109267, 248079,   9089,    248,  75529,    351, 226047,
          6399, 200356, 248079,   2493, 109207, 181953, 248079,    540,  35883,
        120531, 248075,      2])


In [36]:
len(tokens['input_ids'][0])

75

In [37]:
token_embeddings = token_embedding_layer(tokens['input_ids'][0])

print("Token Embedding Matrix shape", token_embeddings.shape)
token_embeddings

Token Embedding Matrix shape torch.Size([75, 1024])


tensor([[-5.0000e+00, -1.2725e+00, -9.3604e-01,  ..., -1.8297e+01,
         -9.1328e+00, -1.0672e+01],
        [ 2.6416e-01,  2.6831e-01,  2.0117e-01,  ...,  3.2715e+00,
         -3.2402e+00,  3.1738e+00],
        [ 4.3579e-01, -2.3352e-01,  2.6825e-02,  ...,  5.4648e+00,
          2.7129e+00,  5.5430e+00],
        ...,
        [ 8.5859e+00, -4.5391e+00, -4.7314e-01,  ..., -7.9529e-02,
          7.4844e+00, -7.5156e+00],
        [-2.4863e+00, -2.7515e-01,  5.6114e-03,  ...,  1.0180e+01,
         -7.2422e+00, -4.8047e+00],
        [-7.8320e-01, -9.0527e-01, -9.4482e-01,  ...,  3.1078e+01,
         -8.1494e-01, -8.7354e-01]], grad_fn=<MulBackward0>)

In [38]:
token_embeddings_np = token_embeddings.detach().numpy()

fig = px.imshow(
    token_embeddings_np,
    color_continuous_scale="RdBu",
    labels=dict(x="Embedding Dimension", y="Token Index", color="Value"),
    title="Token Embedding Heatmap"
)

fig.update_xaxes(side="top")
fig.update_layout(height=500, width=900)
fig.show()

In [39]:
te_values = token_embeddings_np.flatten()

fig_hist = px.histogram(te_values, nbins=100, title='Distribution of Token Embedding Values')

fig_hist.update_layout(
    xaxis_title='Value',
    yaxis_title='Count',
    bargap=0.05,
    showlegend=False
)

fig_hist.show()

In [40]:
print("Token embedding matrix")
print("Min", np.min(token_embeddings_np))
print("Max", np.max(token_embeddings_np))
print("Average", np.average(token_embeddings_np))

Token embedding matrix
Min -30.453125
Max 32.09375
Average -0.4347908


In [41]:
token_embeddings_with_pe = token_embeddings_np + pe_mat

token_embeddings_with_pe.shape

(75, 1024)

In [42]:
fig = px.imshow(
    token_embeddings_with_pe,
    color_continuous_scale="RdBu",
    labels=dict(x="Embedding Dimension", y="Token Index", color="Value"),
    title="Token Embedding with Positional Encoding Heatmap"
)

fig.update_xaxes(side="top")
fig.update_layout(height=500, width=900)
fig.show()

In [43]:
te_with_pe_values = token_embeddings_with_pe.flatten()

fig_hist = px.histogram(te_with_pe_values, nbins=100, title='Distribution of Token Embedding Values with Positional Encoding')

fig_hist.update_layout(
    xaxis_title='Value',
    yaxis_title='Count',
    bargap=0.05,
    showlegend=False
)

fig_hist.show()

In [44]:
print("Token embedding with positional encoding ")
print("Min", np.min(token_embeddings_with_pe))
print("Max", np.max(token_embeddings_with_pe))
print("Average", np.average(token_embeddings_with_pe))

Token embedding with positional encoding 
Min -31.3189225095177
Max 32.09375
Average -0.06121992400905737
